/* Authentication */

export const AUTH_SIGNIN_REQUEST = 'AUTH_SIGNIN_REQUEST';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILURE = 'AUTH_SIGNIN_FAILURE';

export const AUTH_SIGNOUT_REQUEST = 'AUTH_SIGNOUT_REQUEST';
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';
export const AUTH_SIGNOUT_FAILURE = 'AUTH_SIGNOUT_FAILURE';

export const CHANGE_REGION_REQUEST = 'CHANGE_REGION_REQUEST';
export const CHANGE_REGION_SUCCESS = 'CHANGE_REGION_SUCCESS';
export const CHANGE_REGION_FAILURE = 'CHANGE_REGION_FAILURE';

/* Vaults */

export const VAULT_GET_REQUEST = 'VAULT_GET_REQUEST';
export const VAULT_GET_SUCCESS = 'VAULT_GET_SUCCESS';
export const VAULT_GET_FAILURE = 'VAULT_GET_FAILURE';

export const VAULT_UPDATE_REQUEST = 'VAULT_UPDATE_REQUEST';
export const VAULT_UPDATE_SUCCESS = 'VAULT_UPDATE_SUCCESS';
export const VAULT_UPDATE_FAILURE = 'VAULT_UPDATE_FAILURE';

export const VAULT_CREATE_REQUEST = 'VAULT_CREATE_REQUEST';
export const VAULT_CREATE_SUCCESS = 'VAULT_CREATE_SUCCESS';
export const VAULT_CREATE_FAILURE = 'VAULT_CREATE_FAILURE';

export const VAULT_LIST_REQUEST = 'VAULT_LIST_REQUEST';
export const VAULT_LIST_SUCCESS = 'VAULT_LIST_SUCCESS';
export const VAULT_LIST_FAILURE = 'VAULT_LIST_FAILURE';

export const VAULT_DELETE_REQUEST = 'VAULT_DELETE_REQUEST';
export const VAULT_DELETE_SUCCESS = 'VAULT_DELETE_SUCCESS';
export const VAULT_DELETE_FAILURE = 'VAULT_DELETE_FAILURE';

/* Uploads */

export const UPLOAD_CREATE_REQUEST = 'UPLOAD_CREATE_REQUEST';
export const UPLOAD_CREATE_SUCCESS = 'UPLOAD_CREATE_SUCCESS';
export const UPLOAD_CREATE_FAILURE = 'UPLOAD_CREATE_FAILURE';

export const UPLOAD_GET_REQUEST = 'UPLOAD_GET_REQUEST';
export const UPLOAD_GET_SUCCESS = 'UPLOAD_GET_SUCCESS';
export const UPLOAD_GET_FAILURE = 'UPLOAD_GET_FAILURE';

export const UPLOAD_DELETE_REQUEST = 'UPLOAD_DELETE_REQUEST';
export const UPLOAD_DELETE_SUCCESS = 'UPLOAD_DELETE_SUCCESS';
export const UPLOAD_DELETE_FAILURE = 'UPLOAD_DELETE_FAILURE';

export const UPLOAD_UPDATE_REQUEST = 'UPLOAD_UPDATE_REQUEST';
export const UPLOAD_UPDATE_SUCCESS = 'UPLOAD_UPDATE_SUCCESS';
export const UPLOAD_UPDATE_FAILURE = 'UPLOAD_UPDATE_FAILURE';

export const UPLOAD_LIST_REQUEST = 'UPLOAD_LIST_REQUEST';
export const UPLOAD_LIST_SUCCESS = 'UPLOAD_LIST_SUCCESS';
export const UPLOAD_LIST_FAILURE = 'UPLOAD_LIST_FAILURE';

export const UPLOAD_RESTART_REQUEST = 'UPLOAD_RESTART_REQUEST';
export const UPLOAD_RESTART_SUCCESS = 'UPLOAD_RESTART_SUCCESS';
export const UPLOAD_RESTART_FAILURE = 'UPLOAD_RESTART_FAILURE';

/* Retrievals */

export const RETRIEVAL_CREATE_REQUEST = 'RETRIEVAL_CREATE_REQUEST';
export const RETRIEVAL_CREATE_SUCCESS = 'RETRIEVAL_CREATE_SUCCESS';
export const RETRIEVAL_CREATE_FAILURE = 'RETRIEVAL_CREATE_FAILURE';

export const RETRIEVAL_GET_REQUEST = 'RETRIEVAL_GET_REQUEST';
export const RETRIEVAL_GET_SUCCESS = 'RETRIEVAL_GET_SUCCESS';
export const RETRIEVAL_GET_FAILURE = 'RETRIEVAL_GET_FAILURE';

export const RETRIEVAL_UPDATE_REQUEST = 'RETRIEVAL_UPDATE_REQUEST';
export const RETRIEVAL_UPDATE_SUCCESS = 'RETRIEVAL_UPDATE_SUCCESS';
export const RETRIEVAL_UPDATE_FAILURE = 'RETRIEVAL_UPDATE_FAILURE';

export const RETRIEVAL_LIST_REQUEST = 'RETRIEVAL_LIST_REQUEST';
export const RETRIEVAL_LIST_SUCCESS = 'RETRIEVAL_LIST_SUCCESS';
export const RETRIEVAL_LIST_FAILURE = 'RETRIEVAL_LIST_FAILURE';

export const RETRIEVAL_DELETE_REQUEST = 'RETRIEVAL_DELETE_REQUEST';
export const RETRIEVAL_DELETE_SUCCESS = 'RETRIEVAL_DELETE_SUCCESS';
export const RETRIEVAL_DELETE_FAILURE = 'RETRIEVAL_DELETE_FAILURE';

export const RETRIEVAL_RESTART_REQUEST = 'RETRIEVAL_RESTART_REQUEST';
export const RETRIEVAL_RESTART_SUCCESS = 'RETRIEVAL_RESTART_SUCCESS';
export const RETRIEVAL_RESTART_FAILURE = 'RETRIEVAL_RESTART_FAILURE';

/* Inventory */

export const INVENTORY_INIT_REQUEST = 'INVENTORY_INIT_REQUEST';
export const INVENTORY_INIT_SUCCESS = 'INVENTORY_INIT_SUCCESS';
export const INVENTORY_INIT_FAILURE = 'INVENTORY_INIT_FAILURE';

export const INVENTORY_REMOVE_RETRIEVAL = 'INVENTORY_REMOVE_RETRIEVAL';

export const INVENTORY_CANCEL_REQUEST = 'INVENTORY_CANCEL_REQUEST';
export const INVENTORY_CANCEL_SUCCESS = 'INVENTORY_CANCEL_SUCCESS';
export const INVENTORY_CANCEL_FAILURE = 'INVENTORY_CANCEL_FAILURE';

export const INVENTORY_LIST_REQUEST = 'INVENTORY_LIST_REQUEST';
export const INVENTORY_LIST_SUCCESS = 'INVENTORY_LIST_SUCCESS';
export const INVENTORY_LIST_FAILURE = 'INVENTORY_LIST_FAILURE';

export const INVENTORY_UPDATE_REQUEST = 'INVENTORY_UPDATE_REQUEST';
export const INVENTORY_UPDATE_SUCCESS = 'INVENTORY_UPDATE_SUCCESS';
export const INVENTORY_UPDATE_FAILURE = 'INVENTORY_UPDATE_FAILURE';

export const INVENTORY_REMOVE_REQUEST = 'INVENTORY_REMOVE_REQUEST';
export const INVENTORY_REMOVE_SUCCESS = 'INVENTORY_REMOVE_SUCCESS';
export const INVENTORY_REMOVE_FAILURE = 'INVENTORY_REMOVE_FAILURE';

export const ARCHIVE_GET_REQUEST = 'ARCHIVE_GET_REQUEST';
export const ARCHIVE_GET_SUCCESS = 'ARCHIVE_GET_SUCCESS';
export const ARCHIVE_GET_FAILURE = 'ARCHIVE_GET_FAILURE';

export const ARCHIVE_DELETE_REQUEST = 'ARCHIVE_DELETE_REQUEST';
export const ARCHIVE_DELETE_SUCCESS = 'ARCHIVE_DELETE_SUCCESS';
export const ARCHIVE_DELETE_FAILURE = 'ARCHIVE_DELETE_FAILURE';
